// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urfuuwmjeiktlkwntsah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZnV1d21qZWlrdGxrd250c2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NTAxMTUsImV4cCI6MjA1MDAyNjExNX0.2W7lD0xHgf2vwPeyQvwYzXgcCmdwZNymq85Stt4uUrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);